apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-episode-03
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-episode-03
  template:
    metadata:
      labels:
        app: backend-episode-03
    spec:
      containers:
      - name: backend
        image: afnannaseem837/mern-episode-03-backend:latest
        ports:
        - containerPort: 5000
      volumes:
        - name: database-volume-03
          persistentVolumeClaim:
            claimName: db-claim-03
---
apiVersion: v1
kind: Service
metadata:
  name: backend-episode-03
spec:
  selector:
    app: backend-episode-03
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
