apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-episode-03
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-episode-03
  template:
    metadata:
      labels:
        app: frontend-episode-03
    spec:
      containers:
      - name: frontend
        image: afnannaseem837/mern-episode-03-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-episode-03
spec:
  type: NodePort
  selector:
    app: frontend-episode-03
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
