apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-episode-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-episode-02
  template:
    metadata:
      labels:
        app: backend-episode-02
    spec:
      containers:
      - name: backend
        image: afnannaseem837/mern-episode-02-backend:latest
        ports:
        - containerPort: 5000
      volumes:
        - name: database-volume-02
          persistentVolumeClaim:
            claimName: db-claim-02
---
apiVersion: v1
kind: Service
metadata:
  name: backend-episode-02
spec:
  selector:
    app: backend-episode-02
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
