apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-episode-01
spec:
  replicas: 3 # Increasing the number of replicas
  selector:
    matchLabels:
      app: backend-episode-01
  template:
    metadata:
      labels:
        app: backend-episode-01
    spec:
      containers:
      - name: backend
        image: afnannaseem837/mern-episode-01-backend:latest
        ports:
        - containerPort: 5000
      volumes:
        - name: database-volume-01
          persistentVolumeClaim:
            claimName: db-claim-01
---
apiVersion: v1
kind: Service
metadata:
  name: backend-episode-01
spec:
  selector:
    app: backend-episode-01
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
